"""add conversation_reply_log

Revision ID: d6739ea19223
Revises: aceb5ad2a86c
Create Date: 2023-02-23 22:40:18.790170

"""
import sqlalchemy as sa
from sqlalchemy_utils.types.uuid import UUIDType
from sqlalchemy_utils.types.choice import ChoiceType
from alembic import op


# revision identifiers, used by Alembic.
revision = "d6739ea19223"
down_revision = "aceb5ad2a86c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_reply_log",
        sa.Column("id", UUIDType(), nullable=False),
        sa.Column("user_reply", sa.Text(), nullable=False),
        sa.Column("language", ChoiceType([("en", "English"), ("ru", "Russian")], impl=sa.String()), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("content", "audio_url", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("content", "audio_url", existing_type=sa.TEXT(), nullable=False)
    op.drop_table("conversation_reply_log")
    # ### end Alembic commands ###
